#################
### AUTOSTART ###
#################

exec-once = swww-daemon &
exec-once = ~/.config/hypr/additional/wallpaper_random.sh
exec-once = hypridle &
exec-once = waybar &
exec-once = nm-applet --indicator &
# exec-once = blueman-applet &
exec-once = sleep 3 && kdeconnect-indicator &
exec-once = systemctl --user --no-block start hyprpolkitagent.service &
exec-once = systemctl --user --no-block start mako.service &
exec-once = wl-paste --type text --watch cliphist store &
exec-once = wl-paste --type image --watch cliphist store &
exec-once = systemctl --user --no-block start gammastep &
#exec-once = sleep 10 && vesktop --start-minimized &


#############################
### ENVIRONMENT VARIABLES ###
# #############################
# exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
# exec = gsettings set org.gnome.desktop.interface gtk-theme "Materia-light-compact"   # for GTK3 apps
